apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBpxCV73s8BggTb9tefrLNlih8vtOvgX3eIEZfSNZbLG0xEsGRtIltd4jeOIM6leISFPUvUORySnl4df+fZ6xEC+3PEuDUBx4wKlRVp+Hxq6tiAIJlkECPLyDwmbtlgt8NeMYhmfARTLpU5FqO6KmlAmp7Gqs2eyaOrtyHPoybBFWhoeCSxWwK7VI6HAeZPfkpTihsC6E9z7AnwSR77OSwZH8Uw9GFdFeCghMAE5uIUlP1TcZcMaiVpyNsIXwDyxBHdAGwpbWf1+y3UxQNnQOqA04Mh/qEu0UR+P9f9V1danTEHU7ZBqiPC95oE7jQI8Gk5yDYq+aTctCC6YVIrDZrsGN/Om8CqLP7AIQhrWub/Al4/wfwabXsrFX7V9rWVMf+GXWgPNdq5GfpewFGV9Oqy8jdE5ta6mq7wiznYeNWLhtHQ/RlQQy3Rvot2K/McQMQOFibSrxaKMiZnr811jQz3KtrJ9UxQUir3jZE9KkbMRrtDPhbIntSijg6UGR0cyccsQ0MZYAbV3mIIkGLAx70BZ55u8PI/gL6hqh+VYM53FEN3fC4Nsh98fc9WJe0pmhw2QsaL/ODiri9gR6lyG95JwiZ8ReWY4UELns+FSsi/jP3BM+sETapBqciZIidAlNK+CUe9W6DKW0LGuRqXOeYU2nyLRAewZPryDLlBbktr4vWlmtzMYS4XlhM6Gj4XTq9A4uvg2fyN9YQna/3W7deYi22jy7OH5apzvzgZBYVK8xYhj1v5fTdqLffNq3OECAeYaxOKa+EKW0OcCVS6VwZ2ttI3efmmSKCdqgs+xa3rzbRju0sEqtfR09//vQLVaHIrfHsCTiZJPJ1o+pV8nCBw0AKf6SRrZWSmOsaHpbJ1LwEj/n5SIflGkJYkAKp//u/BNP74egfINckGKyddUkToYJ4PpjRV7YggDFKjNvRZSc00NWdosKxj9dVA6Qb81ZWc5ZCf52SIZcuwLdUeYxU01z0Qf07+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

