apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgA8psVgdgbIQWZiS0ed1zKqxRqa/s/Qcv71oO3QMw4tPXbfIZSK7QfQwqLZAAw4JXuz8nRu9aDtM5Q+XSfMeTgURCY03Z08pvqzwpDTXT9izBH2iHPUg64MWZeJ0B+LTAgIFVdOP6RRv79QKJnlwXVyAaUL5N0AkM9TF56uO1IxdaYngnz5fGef2R3K7Zeumz+n6c3EKuEJTtlWS0Szfajt+c09OyEiyFJ7n55+78OwwadWD1e4JHRSsGs6opdOipL8OviKr18UfGdlITV/gX95SSXvKSq1plehXlX1T71CwBJ+ykeEqJ3rMmVMG2YHomlcWnJImSM7JjLQmnsIcOKllDXh+xd27eo3F5WRrUCJsWRzHe6YWRaCBcBeOElET4iOBObwpjzL61c6AbfFHe2/Wz1pmX3KzHeIIJV6Ja23dQ80iHApsR2SpUlVzw5qQxkIHQzaCwmTdtrcmjNNT8IOF+66NfqsGNNvji1xcS7Mrpsht6nlh94wPE1v/fOjo65wlQJqjz2o3VjpONe0GqDwEEj1H8RagTZCTVR/Uuvb/VahYuC78YvA4WVspGsk5xgirYBRawj6ctZUO1XWBWYD6S7qBaAq/aiFctZncbXpIZ/z1oORaGQ/QrM/S6xS5Hwqcj18bEzelzTsBonkBPfgMQqgQTa52rxcU/dWln2ofRbj4KRHsNeatXCMuNpmO9T+XugrRZZtBet8X7maZhxpycGwo2MYmz/fH3DQqecvo2WZveYcQRfFXdcRnk/5f01fyyIMm0EAMVaVY+tVPFx1YhkRXKKsYb6uEV7AUzvaKiLvCx8bDivuHM266z9ziMSkt3DkKd+D2leFxpRbj1QLh9K88mPe+BF2nEQ0sGXQtxJfGRK8oUTqy4dUTdHr4YgvCM10EMmL2fdHpwsDbUd8jrBKznnsS5E/Jp0zfobP8TQPQdZmEeWBQ8jFOI0/LEsAFUNFbHPm9BqYkYDXEt+FhmojQ5Gy
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

