apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCP87zICZstOBW1rIMF7DoXNubFVBMLNTFQ5gadfkxUBGY0dVg9dBh5DSYhJNYASgjkgsRxGDmmQ1KSNa2kXbHLetHKCWZNQ83wy9meWf1B3HfFPYt47XB9XGmPq46/B+kbmIxwCKRIwPe0QYjKweznvB7/jPDGTVG0Vm0eyHeW4Ou7K6Sn4RWOxQn5d5/DHoxAR5oYW8IvqmqZJA1rtvf06xRA0bmnP7I7/aDinwtTD+r84qycuCp890UKcFOM/G/FiE/LRXvJ5tWBZA8d9dtBr25sBGaE4W3ucB1tH92r1zuoEYZFn7A7mzygWPbWeaplVuBOjCkJpvaf8Ei1TZPWw7odiVurgfukDKLoFSQfA2JPELF7IBvDTzOuMkdavUVef55zTxRExOUmmm22rcNkEFIu/Cj2//TbdOAKxdU95k7Yr8vxUGWE0sVhkbQvWC3RCql6scKpyXW1B9VaPkYgIRymScJjEYrFP5HW51lvkJMVj1t9kQ3/27qa4TrJAhfK9wtdFDbtskMzqhrdVZ7D9k2YHxW1mIbAruV9L3V5AZ8sjr5dwzoMmZL8TgKS08iXLi+G/3m+m2hLveldQ4W9Rnwu59bDr50anA3TfgXK+ARG8cjrdEc/sZdGBkora2N27zpZjk9K5V4p0Xi8ZL7S81XLD3eHiOrxXSYLQ/V3U3EC1juA4m1WzkgHort7ATA714fz6hhCpUOHSQma88XqGr9S3FdLeEUi0OPvctgS8ENis0boYrrQZEDj7zeg/Xuo8qkA54D+BtMxg1TZ5hmdqTfXGI139FfP3vTlQJAT1t4YN0eHh2FzSiF0uDVwRP24qXZxW0mKH0FWmwSe8eLQO1SliiwktHOU+KsTtc3tjb9gWAmZTb32tr2RDrQTfXOtSnU5IGbGToezT8COt/QgkvtZy+qijoPedAHf7LpQ+uux2Q4/OTYxHXuhRirl/StTtIoSeuEbFWxfY0kO9LCoPvcfhXay
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

