apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAm3yUkB3fSa4YGO4QPUvh8Ylwtbg08qM1pggy20ivD5klXcu5veGJf96cX++DmEsNWcND4X+nda8jzpcaqf9G5Yqg/kfkfAit6DE9M+ORC7XWteQsZTq1Z5if/qAX/SkilUbdv4ZLFwc8c/yzKB0Cf0cG0CbdXmNbvR97mesIr8Se9Qwn5jc4fCKcy7kacz42yP+CB9fIGAa6ez9VKXEm508+9z06dw884/HBtN7OcPIM6+MLTZO4T0nZzeU/engpcV5bEZHJEyJrk02Z1HhoIDyJ95Ufc4pNNNyalsrZvJs/PmyZupVW4S+lOnnYquAfgkG5j29we7P6ifo5MesoAXgnV+nTZYu7iokZSrhC+PJwnFQiEpRtTqYPVHMYCvwXWAqLs6NQZczWIFpe/BFEn7kwOrBjagLu4KJj4YzPxWb6jw6zDQoF0Yjkpu4GrDb2uRqJA67VqXC05jpymswZjL8B2XHCfe4tsinB4hSqrM243kYgkR3hXOCEteWOx18DlnNXf7JpfS/BTMBtj3jq8OFHpnOXGKKaygINomKBw8uYRrMi4iinBHp6+23w3zMYgpSrLnk+BF38s8dGMGRnX+J/dWYPUYEJrRyBodBhmK8TAVNnu4IV37p9TbSQRrxihhMhZvaVGyOIq1aRqULsFn/t52RnQGATW/xHsytqNsuFUrehYVGs/L79gct95ImAll3NGxkihsPSn19OllsFCiW8Z42A/KR97UCjWMZzso2h7NlFl4wmjcankBSs13nDzfNlkets3UhDC2j9IGb24kLkW3JMsddM72OJF9uhmaolOiUF4mb/uv24WxZAmXLNQsRXh7IZkaQC7EClrDrFn2SWqjORW8SEYLSctXSMIeK0s5ISmTaUuKBKYN/a0O7fMc+6ScZSrmuLuoko+5Rm0qRS1EzZMGu+m8WBJaEOvTwuuSrD2mCo+D1vTeSJIc0KsoS0duXqFCIKFyNWgmLIiHUCJ2eIz
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

