apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCdfUxz4Qo+TqY+xsGFC4hrbxxWgNg8i7il/jtuCB9KXtMj1vvuFV6kdi9QaoLXGYkdswRJ33xgOllBiNSbRZ1gtOk4IUJHA63gZpnMZG34GLChYCFsbI6XUJ5XoAqPrgSYTL2/5s/qtDfWJzghMK0qQTgFYB9yYyWXyCVM7c6jqZb7VagRvG+Rg3cny01dLOivOGgqT2tIV3FTUkLYj1VwIbBGzXuUeHFJwgP8+ELlOZvsqy23ek0DwMZhA83WQjAKKYLgN0ZdN0p6IC9Gf/UqNIlq2oPf786HVpWnSInfZqNIKWvFhNxAqQg8B3EQg8Ec6JhvpnssCSbejn3Ckegw8bEqQxOB5b4nxFUM/MmiDZvJ8hgt8qHxtYWhZH3HNtJBHeLbMRoiiYekS2CJnxR3zWUnU/+G2Dvrfz9TIRpq44rzWRjzTggoEBIcln079CEjLoAv61cZyfZ+R04NUBVUkcL7hZOvoUbdE51TM6bOI8+Z8tXdePlFxVuc35x0daVfJjJMCCRXQn1lUCoAGo2w+qfXvu3l6h8jsJnlIyi14ZmsK72QsOEGxTNE7TmjILH54bHQQrNjxy8RralCZs8aqdlKIAl85tVxBPQWH/rYqkOndtlbLqJVBl4XYG6cvwZXvJ7iolyE8xD9eFA3zKWUUNL9m+hvmDwCyyeb9z+64WbSxovpSHZnQqCikYMv294xMiOv9DCFlRUB5gDVmv/tBUX0GwejIIW7x2JILV7xLf0U3GewUIbV
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

