apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgA1nlQtMMp5k7g1ptuIvz9xQFElVyST95XSRxKkrw3kZAq8o+wAzSFODp/8BGlZP8h+3mnRvFqI/+vmAIyeyzbWe4qS0RFnL0OaGFR/iXJfck+2gEzrN6DJi0i65E2uHuUswQvMjlXd3IQGk0Op1q0gC7C+AuvDLkzkUpSDdFKtK7H2Gvm3Tn9UJX9wbe/NQ5/xesQPqIzSK8YHHYNzFIrLft5YlwC0ZGG2199Wg67dD68tL16c6FHyAh3v57mz/3fQ2YhXL0pGdpay5GxAuGeDGvS5H42CeTW52unepnaeXADnrMESQxWt/vrZEvsz3XivxfiC5Bc/XIDtLug2Ysc26Qu1nSJiYgvZe9sqayFrCNTfGBB1fKIfz4MDQbZ5cCt4fKB621QK04QEZA5GG4aYDlw5DSsayeYyKK2bWO9xRwOCfnA1kq9pz4Cw/eSIIiS+s8wPccS3thRJTwB2idny4qTFB5HlpBkE4GyZozqPI1idCQzui7gajRBUVHeux83jTY9gXS0VQRp7VdKtnXc8M3kf4fdGnOD7H6EjAOnfF1PINs76ptE74Lw56Ov1ZXxfAgDIap2tY1Cf2s3bv3hJskG1vmVWi1OQ2DP67XXCoX3vYAWlJNRZvUuxnULNZyXYqbeLvsT7CjFdnYkMyHW4JWZmZz1D4od6tAOdowtb/x4ZY1pVdhwQPkycsBqtSuyQTTogcWjgSQJ17muckTA83UhxxD/f4PUjguj2G3GUf8sKZXnp91gE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

