apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBE1l3xCEMI3sAd3tlCVBNDoEjPHkAkcNJd8kEQiRt1wnLmZrXG1dARpWG4sC+qM/DR7WFj6AFs415vSJvpTw/00ytjBvyNYEjMC5WKnX/2oL9fTcG+ACLBYz/fuZHu3EBJOAsQRV65AjysNdTVVmX8ymwsWas+qo7YfGunhTIO4q3LHOSuN33km76bGu/IGlYvChb2eDL/A2L95cWlq5xvjzzUEIl7Z6DXBYrLzVy9Okhy1v6lyQb4H2JKXo5jwSVPI6DQOiIQNHjGntI5g15rV5HvjNx6tbn/hEdUo4554MLnqH9cCRLjqTXa7enrEJvDbV4geGHxovQr81gdgK+Il27GKulaAW3FFyLel846eIDFBsxodZFbYpPQlH+2Yv1h9giKGXSUB9/qF3/Tybj+uGbDLoV21bNrgA2xKKYGKrVbFCBDcI0URHLm9BHYIeK0ckoIEfnz3XbkKhQ8vVvYcUUM96/s31bDzahC3lM80/RNjpE1c8R3dJIBufVq0WAUF5kiSy/qZjEu7Zhum0/Zl42FzAqYIf+BUAEYiUTUogW8DSFRMNWofQm809kZ3zgVQRgliS2m+I+PBO+Z7afxrYWAnQUStagEU0nWqT9N14KlEiL73e9ME+E/b9RRHeHtQQ17hqky0F2/sC8MaibXME9lHqxvcyYFz97MPiFKopkylYg7xpnEFWlIg9o1Hp5q/H1MqfpKedP6iahcVYCLCtB8ivbsm5Gg5i/iOy7L9uWHdFG23q62
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

