apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBBcyr1CnSN6J6f0NRI8393iurl0GwwVndSIYr9BMGTiK/jSU9r6goZ6/p8gZQ3YO5K2KmI35yxhcrtYW+fpVLJS9Hqi9Gw0Eti9wgF3Erg6COUTsOzs6jAbDY5uGjp0NRwPdfYOb4UDg5TqRX2v8YMoZ9+wZCqNGSD2lbwy5lSBbbVIAawv0dhl884MavVNb4HibCNLhy6Tm46kuV6ei3UZdwcuem+nHuh+xxHtE6Evb1K+UCsyrbLBSXYtD/KaRCGWxYYNnzb/kQwArVM/668qFxyptpcGSONYC8V7SoKCVxicUF6LQlVyI+SoNOlaoRWmCNvGXeUP+/EgZZd6XQKTFi9oIuH72eDofjy5SwGt26bpW4EMbT3wQtxFtl3PXKwVs4+xP5k9GyNomiNd6IaIYLno9adVBmnHLVAudDthW65+MKpyAzkWk//XqgZvQAWsK2OhgS4pwmyczpGdw/HUBZ5bZE3h+sK3/m1/4j3ZUAMeXwfio8OZXWAdM8MsQ3KddPPCmRgdDcJ+WEUarb+mXaGpDgGQD51BFkhGTnUPK86JykoHWHiujlsHWt2wuMIYo8NprAnyBcQpxCy6x5GXdmBUbB/WiLhz4/0e+3c/1okm/6VoO9Z2pmSEbWT4s9EQ5BuZ7/oR/1veeNtiTvEJGlkW2hECxS4F+GB/j+sF7dSV3VDRAqqEvF91p8pJdaOCtXwPHcORrE2ISfQAnU/hdLM8AVIEsT7MLKSGjJ7rNJxkKQDGNkc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

